include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_print: false
    prefer_relative_imports: true
    public_member_api_docs: false
